all:	
	g++ -o main ./src/main.cpp ./src/common/controls.cpp ./src/common/objloader.cpp ./src/common/shader.cpp ./src/common/texture.cpp -Wall -lGLU -lGL -lglfw -lGLEW

run:	
	g++ -o main ./src/main.cpp ./src/common/controls.cpp ./src/common/objloader.cpp ./src/common/shader.cpp ./src/common/texture.cpp -Wall -lGLU -lGL -lglfw -lGLEW
	main
